name: Build

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build plugin
      run: xmake build -y linux
    - name: Pack plugin
      run: xmake pack audioplayer_linux
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: audioplayer_linux
        path: build/xpack/audioplayer_linux/audioplayer_linux.zip
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build plugin
      run: xmake build -y windows
    - name: Pack plugin
      run: xmake pack audioplayer_windows
    - name: Upload plugin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: audioplayer_windows
        path: build/xpack/audioplayer_windows/audioplayer_windows.zip
